# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    fos_user.registration_success_subscriber:
        class: AppBundle\EventListener\RegistrationSuccessListener
        arguments: ["@router"]
        tags:
            - { name: kernel.event_subscriber, event: fos_user.registration.success }

    app.share_data_import:
        class:     AppBundle\Service\YahooShareDataImport
        arguments: []
